### ISSUE TITLE
I wonder if GH can allow anyhow to upload the stuff the way so that it could be downloaded without a zip

### ISSUE THREAD

**Issue by KOLANICH** [alexbakker/github-artifact-proxy#1]
https://github.com/KOLANICH-libs/miniGHAPI.py/blob/master/miniGHAPI/undocumented.py

They use dictionaries within json. These ones were recovered mostly from mitmproxy dumps (one can try fork https://github.com/KOLANICH-GHActions/mitmproxy and experiment on it), but I suspect that there can be other keys in them controlling the way files are served to users.

**Comment by alexbakker** [comment]
Interesting research, but I'd rather rely on documented API's, so that the service doesn't suddenly break when GitHub changes an undocumented API.
